In [1]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [6]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

# Loading the data set

In [7]:
filepath='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [8]:
df=pd.read_csv(filepath)
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

# Data Preprocessing

In [9]:
# Change categorical variables to binary codes
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [15]:
# Replace caterical column column to binary column
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

In [13]:
#Training Data and Test Data
df_sydney_processed.drop('Date',axis=1,inplace=True)
df_sydney_processed = df_sydney_processed.astype(float)

features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

ValueError: could not convert string to float: 'Yes'

## Linear Regression

In [14]:
X_train, X_test, Y_train, Y_test=train_test_split(features, Y, test_size=0.2, random_state=10)

#Lnear Reg Model
LinearReg=LinearRegression()
LinearReg.fit(X_train, Y_train)

NameError: name 'features' is not defined

In [17]:
# predictions
predictions = LinearReg.predict(X_test)

In [19]:
# Accuracy Evaluations
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

LinearRegression_MAE = mean_absolute_error(Y_test, predictions)
LinearRegression_MSE = mean_squared_error(Y_test, predictions)
LinearRegression_R2 = r2_score(Y_test, predictions)

In [3]:
# Create a DataFrame
Report = pd.DataFrame({
    'Metric': ['Mean Absolute Error', 'Mean Squared Error', 'R^2 Score'],
    'Linear Regression': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})

# Display the DataFrame
print(Report)

NameError: name 'pd' is not defined

## KNN Modelling

In [23]:
k = 4
#Train Model and Predict  
KNN = KNeighborsClassifier(n_neighbors = k).fit(X_train, Y_train)
print(KNN)

KNeighborsClassifier(n_neighbors=4)


In [25]:
predictions = Yhat = KNN.predict(X_test)
Yhat[0:5]

array([0., 0., 1., 0., 0.])

In [33]:
KNN_Accuracy_Score = metrics.accuracy_score(Y_train, KNN.predict(X_train))
KNN_JaccardIndex = metrics.accuracy_score(Y_test, Yhat)
KNN_F1_Score = f1_score(Y_test, Yhat)

results_df = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score'],
    'KNN': [KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]
})
print(results_df)

           Metric       KNN
0  Accuracy Score  0.858180
1   Jaccard Index  0.818321
2        F1 Score  0.596610


## Decision Tree

In [34]:
Tree = DecisionTreeClassifier(criterion='entropy', max_depth=4)
Tree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [38]:
# Initialize the Decision Tree model
Tree = DecisionTreeClassifier()

# Fit the model to the training set
Tree.fit(X_train, Y_train)

# Make predictions on the test set
predictions = Tree.predict(X_test)

# Display the first 5 predictions and true labels
print("Predictions:", predictions[0:5])
print("True Labels:", Y_test[0:5])

Predictions: [0. 0. 1. 0. 0.]
True Labels: 3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64


In [39]:
#Evaluation
Tree_Accuracy_Score = accuracy_score(Y_test, predictions)
Tree_JaccardIndex = jaccard_score(Y_test, predictions, average='weighted')
Tree_F1_Score = f1_score(Y_test, predictions, average='weighted')

# Display the results
print("Decision Tree Accuracy Score:", Tree_Accuracy_Score)
print("Decision Tree Jaccard Index:", Tree_JaccardIndex)
print("Decision Tree F1 Score:", Tree_F1_Score)

Decision Tree Accuracy Score: 0.7587786259541984
Decision Tree Jaccard Index: 0.6251833122895402
Decision Tree F1 Score: 0.7595611837740276


## Logistic Regression

In [54]:
X_train, Y_test, Y_train, Y_test = train_test_split(features, Y, test_size=0.2, random_state=1)

LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,Y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [55]:
predictions = LR.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [56]:
predict_proba =LR.predict_proba(X_test)

print("Prediction Probabilities:")
print(predict_proba[:5])

Prediction Probabilities:
[[0.91834323 0.08165677]
 [0.79529862 0.20470138]
 [0.03873044 0.96126956]
 [0.75118126 0.24881874]
 [0.95217423 0.04782577]]


In [57]:
# Calculate metrics
LR_Accuracy_Score = accuracy_score(Y_test, predictions)
LR_JaccardIndex = jaccard_score(Y_test, predictions, average='weighted')
LR_F1_Score = f1_score(Y_test, predictions, average='weighted')

# Display the results
print("Logistic Regression Accuracy Score:", LR_Accuracy_Score)
print("Logistic Regression Jaccard Index:", LR_JaccardIndex)
print("Logistic Regression F1 Score:", LR_F1_Score)

Logistic Regression Accuracy Score: 0.6244274809160305
Logistic Regression Jaccard Index: 0.47139756151070006
Logistic Regression F1 Score: 0.6079164376769491


In [58]:
# Note: log_loss requires predicted probabilities, not just class labels
predict_proba = LR.predict_proba(X_test)
LR_Log_Loss = log_loss(Y_test, predict_proba)

print("Logistic Regression Log Loss:", LR_Log_Loss)

Logistic Regression Log Loss: 0.9337522133715982


## Support Vector Machine

In [59]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(X_train, y_train) 

SVC()

In [60]:
predictions = SVM.predict(X_test)
predictions [0:5]

array([0., 0., 0., 0., 0.])

In [61]:
# Calculate metrics
SVM_Accuracy_Score = accuracy_score(y_test, predictions)
SVM_JaccardIndex = jaccard_score(y_test, predictions, average='weighted')
SVM_F1_Score = f1_score(y_test, predictions, average='weighted')

In [62]:
# Create a DataFrame
Report = pd.DataFrame({
    'Metric': ['Accuracy Score', 'Jaccard Index', 'F1 Score','LR_Log_Loss'],
    'SVM': [SVM_Accuracy_Score, SVM_JaccardIndex, SVM_F1_Score, LR_Log_Loss]
})

# Display the DataFrame
print(Report)

           Metric       SVM
0  Accuracy Score  0.722137
1   Jaccard Index  0.521482
2        F1 Score  0.605622
3     LR_Log_Loss  0.933752
